# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  #连接超时时间
  connection-timeout: 5000ms
  # servlet:
  #   #映射项目路径
  #   context-path: /blog


spring:
  servlet:
    multipart:
      #文件上传大小配置
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    #restFul风格：当找不到页面时，正常抛出错误，不跳转页面
    throw-exception-if-no-handler-found: true
    #仅映射static资源文件
    static-path-pattern: /static/**
  resources:
    #restFul风格: 不要为资源文件建立映射
    add-mappings: false
    static-locations: classpath:/static/,classpath:/public/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/dbblog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6s #连接池超时时长
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接
    password: 123456
  # elasticsearch配置
  data:
    elasticsearch:
      cluster-name: gaoh
      cluster-nodes: 127.0.0.1:9300
  # rabbitMQ配置
  rabbitmq:
    host: 123.57.215.33
    port: 5672
    username: guest
    password: guest
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
    serialization:
      # jackson返回时间戳
      write-dates-as-timestamps: true
  #开启AOP
  aop:
    proxy-target-class: true
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  resource:
    static-locations: classpath:/static/,classpath:/public/
#mybatis
mybatis-plus:
  #mapper文件
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: org.gaoh.modules.entity.manage
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
    #刷新Mapper，只在开发环境打开
    refresh: true

  #mybatis原生配置
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    #不开启二级缓存
    cache-enabled: false
blog:
  path:
    #文件上传根目录 设置
    upload: D://upFiles
    #webapp文件路径
    webapp: D://webapp
  #短信秘钥
  sms:
    accessKeyId: LTAIcuaV1o8Vp2fZ
    accessKeySecret: hpYKjWmqqNvUZDvVrmZQ9D2alWPpOd
  #阿里云oss存储配置
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKey: LTAI4GKNwbN6615t6ntCDF3V
    secretKey: 8pbAdBEWMvT2fSIPd8bGkRuvdl6Atc
    bucketName: gaohoos
    staticDomain: ??
  shiro:
    excludeUrls: /admin/sys/user/list
oss:
  qiniu:
    domain: http://oss.dblearn.cn
    prefix: dbblog
    accessKey: ENC(pVGOa/io1AnqiEKkDTVORO3W8nzn+vbOl53TeRBIGgCuWvqUEzOAdIBLmdpoYVmsDHESGVc2QzY=)
    secretKey: ENC(UXM3TEuaIuLrPdKuDASHoZExQyOrgGl7PqV/iB0EbHOFhnUSF3bMol8D2qh+QlthccS5QD0fHbM=)
    bucketName: test

jasypt:
  encryptor:
    password: dbblog-jasypt

project:
  path:
    #文件上传根目录 设置
    upload: D://upFiles?usr//local//upFiles
    #webapp文件路径
    webapp: D://webapp?usr//local//webapp
swagger:
  is:
    enable: true
logging:
  level:
    com.gaoh: debug